tony_base:
    resource:   "@TonyBaseBundle/Controller/"
    type:       annotation
    prefix:     /

tony_user:
    resource:   "@TonyBaseBundle/Controller/"
    type:       annotation
    prefix:     /

proj_core:
    resource:   "@ProjCoreBundle/Controller/"
    type:       annotation
    prefix:     /