proj_core:
    resource: "@ProjCoreBundle/Resources/config/routing.yml"
    prefix:   /

tony_base:
    resource: "@TonyBaseBundle/Resources/config/routing.yml"
    prefix:   /

tony_user:
    resource: "@TonyUserBundle/Resources/config/routing.yml"
    prefix:   /

