security:
    encoders:
        Tony\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       10
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
            chain_provider:
                chain:
                    providers: [in_memory, user]
            in_memory:
                memory:
                    users:
                        lucups: { password: kkkk, roles: ROLE_ADMIN }
            user:
                entity:
                    class: Tony\UserBundle\Entity\User

    firewalls:
#        admin_area:
#            pattern:   ^/admin/
#            anonymous: ~
#            form_login:
#                check_path: _admin_login_check
#                login_path: _admin_login

                # field names for the username and password fields
#                username_parameter: _username
#                password_parameter: _password
                # success_handler: user.login_success_handler
#            logout:
#                path:   _admin_logout
#                target: _admin_index

        user_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                check_path: _login_check
                login_path: _login

                # field names for the username and password fields
                username_parameter: _username
                password_parameter: _password
                success_handler: user.login_success_handler
#            remember_me:
#                token_provider: name
#                key: someS3cretKey
#                name: NameOfTheCookie
#                lifetime: 3600 # in seconds
#                path: /foo
#                domain: somedomain.foo
#                secure: false
#                httponly: true
#                always_remember_me: false
#                remember_me_parameter: _remember_me
            logout:
                path:   _logout
                target: _index

    access_control:
        - { path: ^/user/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
