parameters:
#    tony_base.example.class: Tony\BaseBundle\Example

services:
#    tony_base.example:
#        class: %tony_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
